
[colors]
draw_bold_text_with_bright_colors = true

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

# [general]
# live_config_reload = true

[terminal]

[colors.bright]
black = "0xa6896b"
blue = "0xF35645"
cyan = "0xFAD32F"
green = "0xEB3247"
magenta = "0xF6A73B"
red = "0x5F4149"
white = "0xeec49a"
yellow = "0xBC4349"

[colors.cursor]
cursor = "0xeec49a"
text = "0x0a1124"

[colors.normal]
black = "0x0a1124"
blue = "0xF35645"
cyan = "0xFAD32F"
green = "0xEB3247"
magenta = "0xF6A73B"
red = "0x5F4149"
white = "0xeec49a"
yellow = "0xBC4349"

[colors.primary]
background = "0x0a1124"
foreground = "0xeec49a"

[cursor]
style = "Underline"

[env]
TERM = "xterm-256color"

[font]
size=12.0
# normal = { family = "FantasqueSansMono Nerd Font Mono", style = "Regular" }
normal = { family = "Delugia Book", style = "Regular" }
bold_italic = { style="Italic"}
bold = { style="bold" }
italic = { style="Italic" }

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
program = "/bin/zsh"
args = ["--login"]

[window]
decorations = "full"
dynamic_padding = true
title = "Alacritty@Ubuntu"
opacity = 0.9
# save_to_clipboard = true
# "window.dynamic_title" = true
# gtk_theme_variant = "dark"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 100
lines = 30

[keyboard]
