#!/usr/bin/env zsh

# Some useful options (man zshoptions)
setopt autocd extendedglob nomatch menucomplete
setopt interactive_comments
# stty stop undef # Disable ctrl-s to freeze terminal.

# Disable highlighting paste text.
zle_highlight=('paste:none')

# completions
autoload -U +X compinit && compinit
zstyle ':completion:*' menu select
# zstyle ':completion:complete:lsof:*' menu yes select

# compinit
zmodload zsh/complist
_comp_options+=(globdots) # Include hidden files.

# Up-And-Down Arrow for searching history.
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

# Colors
autoload -Uz colors && colors

# Zsh AutoLoad / FPATH
# source: https://stackoverflow.com/a/63661686
() {
    # add our local functions dir to the fpath
    local funcs=$HOME/.config/zsh/functions

    # FPATH is already tied to fpath, but this adds
    # a uniqueness constraint to prevent duplicate entries
    typeset -TUg +x FPATH=$funcs:$FPATH fpath

    # Now autoload them
    if [[ -d $funcs ]]; then
        autoload ${=$(cd "$funcs" && echo *)}
    fi
}

# Source common configuration.
[ -f $HOME/.config/shell/common ] && source $HOME/.config/shell/common

# Cursor Shape
preexec() {
	# Set cursor style (DECSCUSR), VT520.
	# 0  ⇒  blinking block.
	# 1  ⇒  blinking block (default).
	# 2  ⇒  steady block.
	# 3  ⇒  blinking underline.
	# 4  ⇒  steady underline.
	# 5  ⇒  blinking bar, xterm.
	# 6  ⇒  steady bar, xterm.
  echo -ne '\e[4 q'
}

# Source Plugins
_LOAD_ZSH_PLUGINS=${_LOAD_ZSH_PLUGINS:-1}
if [ $_LOAD_ZSH_PLUGINS -eq 1 ]
then

  # ssh-agent settings
  zstyle :plugins:ssh-agent agent-forwarding yes
  zstyle :plugins:ssh-agent lazy yes
  zstyle :plugins:ssh-agent quiet yes

  for plug in git ssh-agent zsh-autosuggestions zsh-syntax-highlighting
  do
    if [ -f "$HOME/.config/zsh/plugins/${plug}.plugin.zsh" ]; then
      source "$HOME/.config/zsh/plugins/${plug}.plugin.zsh"
    elif [ -f "$HOME/.config/zsh/plugins/${plug}/${plug}.plugin.zsh" ]; then
      source "$HOME/.config/zsh/plugins/${plug}/${plug}.plugin.zsh"
    fi
  done
fi
